modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="sosorgans"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.sosorgans]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.sosorgans]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.sosorgans]]
    modId="sons_of_sins"
    mandatory=true
    versionRange="[1.20.1-2.0.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sosorgans]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.20.1-81,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sosorgans]]
    modId="jei"
    mandatory=false
    versionRange="[1.20.1-15.2.0.27,)"
    ordering="AFTER"
    side="BOTH"